version: 1.0.{build}
os: Visual Studio 2017
skip_tags: true
configuration: Release

environment:
  sonarqubetoken:
    secure: ppdeirHI9dsM7NpQgtwIRqXbiqhJZvIyHxOFhnME5HhRFS6IbYZqRppQi7fTqv37

before_build:
  - ps: .\scripts\set-version.ps1
  - cmd: dotnet --info
  - cmd: dotnet restore
  - choco install opencover.portable
  - choco install codecov
  - choco install xunit
  - choco install "msbuild-sonarqube-runner" -y

build_script:
  - SonarScanner.MSBuild.exe begin /k:"SolToSharpLogic" /d:sonar.organization="devedse-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%sonarqubetoken% /d:sonar.cs.opencover.reportsPaths=".\SolToSharpLogic.Coverage.xml" /d:sonar.coverage.exclusions="SolToSharpLogic.ConsoleApp/**/*.cs,SolToSharpLogic.Tests/**/*.cs"
  - cmd: dotnet build -c Release
  - OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test .\SolToSharpLogic.Tests\SolToSharpLogic.Tests.csproj -c Release" -oldstyle -returntargetcode -output:.\SolToSharpLogic.Coverage.xml -filter:"+[SolToSharpLogic*]*"
  - SonarScanner.MSBuild.exe end /d:sonar.login=%sonarqubetoken%
  - codecov -f "SolToSharpLogic.Coverage.xml"

#test_script:
#  - cmd: dotnet test -c release SolToSharpLogic.Tests\SolToSharpLogic.Tests.csproj
  
after_test:
  - cmd: dotnet pack -c Release SolToSharpLogic\
  - cmd: Scripts\GoRepack.cmd

artifacts:
- path: Scripts\SolToSharpLogic.7z
  name: droppackage7z
- path: Scripts\SolToSharpLogic.zip
  name: droppackagezip
- path: 'SolToSharpLogic\bin\Release\*.nupkg'
  name: nugetPackages

deploy:
- provider: GitHub
  auth_token:
    secure: do7S++r1rE5E3IZujCoMONsWYJNF7eoRoPyJbxSD851I850OlEq0gsHH/Tji7o00
  artifact: droppackage7z,droppackagezip,nugetPackages
- provider: NuGet
  api_key:
    secure: pVOzQthQbu7P9SUQwjG43ZEMcwAp7dVbe4BkDVEwJFu1gWK+L11L9mdfGLC5iO5Z
  skip_symbols: true
  artifact: /.*\.nupkg/